name: create branch
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: create barnch
        uses: peterjgrainger/action-create-branch@v2.2.0
        with:
          branch: 'release-notes'